import { ArrowLeft, ArrowUpRight, Bird } from 'lucide-react';

const products = [
  'Bebedouro tubular 50 ml','Bebedouro tubular 100 ml','Bebedouro tubular 200 ml','Bebedouro automático','Bebedouro de bico curto','Bebedouro de bico largo','Bebedouro com presilha','Bebedouro para voadeira','Kit com 2 bebedouros','Kit com 4 bebedouros',
  'Poleiro de madeira 15 cm','Poleiro de madeira 20 cm','Poleiro de madeira 30 cm','Poleiro de galho natural','Poleiro plástico curto','Poleiro plástico longo','Poleiro com fixação lateral','Poleiro para voadeira','Kit com 2 poleiros','Kit com 4 poleiros',
  'Gaiola compacta','Gaiola com bandeja removível','Gaiola com portas laterais','Gaiola para transporte','Gaiola de criação','Gaiola de criação com divisória','Gaiola modelo amplo','Voadeira pequena','Voadeira média','Voadeira ampla',
];
const slugify = (name: string) => name.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
export function generateStaticParams() { return products.map((name) => ({ slug: slugify(name) })); }
export function generateMetadata({ params }: { params: { slug: string } }) { const name = products.find((item) => slugify(item) === params.slug) ?? 'Produto'; return { title: `${name} | Canário Pé Duro`, description: `Confira detalhes de ${name}.` }; }
export default function ProductPage({ params }: { params: { slug: string } }) {
  const name = products.find((item) => slugify(item) === params.slug) ?? 'Produto';
  const category = name.toLowerCase().includes('bebedouro') || name.toLowerCase().includes('kit com') && params.slug.includes('bebedouro') ? 'Bebedouros' : name.toLowerCase().includes('poleiro') ? 'Poleiros' : 'Gaiolas';
  return <main className="product-page"><header className="product-page-header wrap"><a className="brand" href="/"><span className="brand-icon"><Bird size={30}/></span><span>CANÁRIO<strong>PÉ DURO<span className="brand-dot">.</span></strong></span></a><a className="back-link" href="/"><ArrowLeft size={18}/> Voltar para produtos</a></header><section className="product-detail wrap"><div className="detail-empty"><span>SEM FOTO</span><p>Espaço para foto do produto</p><small>Você pode adicionar a imagem depois.</small></div><div className="detail-copy"><span className="eyebrow">{category}</span><h1>{name}</h1><p className="detail-description">Escolha a opção ideal para o seu canário e confira os detalhes antes de comprar.</p><div className="detail-fields"><div className="option-group"><span className="option-label">Tamanho</span><div className="size-options" role="group" aria-label={'Tamanho de '+name}>{['Único','Pequeno','Médio','Grande'].map((size, index) => <button className={index === 0 ? 'size-option selected' : 'size-option'} type="button" key={size}>{size}</button>)}</div></div><div className="option-group"><span className="option-label">Coloração</span><div className="color-options" role="group" aria-label={'Coloração de '+name}>{[['Natural','#c9a66b'],['Amarelo','#f4cf37'],['Branco','#f4f3eb'],['Verde','#607d5d']].map(([color, value], index) => <button className={index === 0 ? 'color-option selected' : 'color-option'} style={{'--color': value} as React.CSSProperties} type="button" aria-label={color} title={color} key={color}></button>)}</div></div></div><div className="detail-purchase"><span>Preço a definir</span><button disabled>Em breve <ArrowUpRight size={17}/></button></div><div className="detail-note">As fotos, preços, estoque e pagamento serão adicionados quando o catálogo estiver pronto.</div></div></section></main>;
}

